# Generated by Django 5.1.1 on 2024-10-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_finder_app', '0002_customuser_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='userid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='imageurl',
            field=models.ImageField(default='path/to/default_image.jpg', upload_to='images/'),
        ),
    ]
